### ISSUE TITLE
Problems running mix test

### ISSUE THREAD

**Issue by jonathanxie** [Dania02525/Restapp#2]
Thanks for creating this! I needed something like this for reference.

After running mix test, 2 tests fail:

```
 1) test json (Restapp.InvoiceControllerTest)
     test/invoice_controller_test.exs:18
     ** (Phoenix.Router.NoRouteError) no route found for POST /invoices (Restapp.Router)
     stacktrace:
       (restapp) web/router.ex:1: Restapp.Router.match/4
       (restapp) lib/phoenix/router.ex:2: Restapp.Router.call/2
       test/invoice_controller_test.exs:24



  2) test get index (Restapp.InvoiceControllerTest)
     test/invoice_controller_test.exs:28
     ** (Phoenix.Router.NoRouteError) no route found for GET /invoices (Restapp.Router)
     stacktrace:
       (restapp) web/router.ex:1: Restapp.Router.match/4
       (restapp) lib/phoenix/router.ex:2: Restapp.Router.call/2
       test/invoice_controller_test.exs:29
```

After changing `invoice_controller_tests.exs` to include `api` in the route at lines 25 and 29,

``` elixir
response = Restapp.Router.call(conn(:post, "/api/invoices",  body, headers: [{"content-type", "application/json"}]) |> Plug.Conn.fetch_params(), @opts)

response = Restapp.Router.call(conn(:get, "/api/invoices") |> Plug.Conn.fetch_params(), @opts)
```

The following errors happen:

```
  1) test json (Restapp.InvoiceControllerTest)
     test/invoice_controller_test.exs:20
     ** (Plug.Conn.WrapperError) ** (UndefinedFunctionError) undefined function: nil.encode/1
     stacktrace:
       nil.encode(%{description: "Unauthorized", error: "Unauthorized", status_code: 401})
       (restapp) web/token_plug.ex:31: PlugToken.create_401_response/3
       (restapp) web/router.ex:12: Restapp.Router.user/2
       (restapp) lib/phoenix/router.ex:2: Restapp.Router.call/2
       test/invoice_controller_test.exs:26



  2) test get index (Restapp.InvoiceControllerTest)
     test/invoice_controller_test.exs:30
     ** (Plug.Conn.WrapperError) ** (UndefinedFunctionError) undefined function: nil.encode/1
     stacktrace:
       nil.encode(%{description: "Unauthorized", error: "Unauthorized", status_code: 401})
       (restapp) web/token_plug.ex:31: PlugToken.create_401_response/3
       (restapp) web/router.ex:12: Restapp.Router.user/2
       (restapp) lib/phoenix/router.ex:2: Restapp.Router.call/2
       test/invoice_controller_test.exs:31

```

To fix that, I needed to add in the following to `test.exs`:

``` elixir
config :joken,
  secret_key: "test",
  algorithm: :HS256,
  json_module: JWT.Module   
```

After that I run `mix test` again and I get these errors:

```
  1) test get index (Restapp.InvoiceControllerTest)
     test/invoice_controller_test.exs:30
     Assertion with == failed
     code: response.status() == 200
     lhs:  401
     rhs:  200
     stacktrace:
       test/invoice_controller_test.exs:32



  2) test json (Restapp.InvoiceControllerTest)
     test/invoice_controller_test.exs:20
     Assertion with == failed
     code: response.status() == 201
     lhs:  401
     rhs:  201
     stacktrace:
       test/invoice_controller_test.exs:27
```

I then tried putting in the JWT as a `token` parameter in the header:

``` elixir

  test "json" do
      body = "{\"data\":{\"contact_id\":\"2\",\"txn_date\":\"2015-03-31\",\"note\":\"test note\",\"po_number\":\"18754b\"},
      \"includes\":[
      {\"product_id\":\"1\",\"income_account_id\":\"1\",\"sku\":\"6558\",\"description\":\"widget\",\"sell_price\":\"18.43\",\"cost\":\"7.24\",\"msrp\":\"19.99\",\"tax\":\"1.48\"},
      {\"product_id\":\"2\",\"income_account_id\":\"2\",\"sku\":\"8000\",\"description\":\"gadget\",\"sell_price\":\"3.36\",\"cost\":\"1.73\",\"msrp\":\"12.64\",\"tax\":\"0.34\"}
      ]}"
    response = Restapp.Router.call(conn(:post, "/api/invoices",  body, headers: [{"content-type", "application/json"}, {"token", "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiMTIzNDU2Nzg5IiwiYXVkIjoidXNlciJ9.xlxDqwfZXlWhKgjXB-QquIP4wRh5xsvCe1Slt8W-W_U"}]) |> Plug.Conn.fetch_params(), @opts)
    assert response.status == 201   
  end

  test "get index" do
    response = Restapp.Router.call(conn(:get, "/api/invoices", headers: [{"content-type", "application/json"}, {"token", "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiMTIzNDU2Nzg5IiwiYXVkIjoidXNlciJ9.xlxDqwfZXlWhKgjXB-QquIP4wRh5xsvCe1Slt8W-W_U"}]) |> Plug.Conn.fetch_params(), @opts)
    assert response.status == 200
  end  
```

By adding in the JWT as a header paramteter, I get one assertion error:

```
.

  1) test get index (Restapp.InvoiceControllerTest)
     test/invoice_controller_test.exs:30
     Assertion with == failed
     code: response.status() == 200
     lhs:  401
     rhs:  200
     stacktrace:
       test/invoice_controller_test.exs:32

.

Finished in 0.2 seconds (0.08s on load, 0.1s on tests)
3 tests, 1 failures
```

Running the server and going to `http://localhost:4000/login/user` does produce:

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiMTIzNDU2Nzg5IiwiYXVkIjoidXNlciJ9.xlxDqwfZXlWhKgjXB-QquIP4wRh5xsvCe1Slt8W-W_U

Going to `http://localhost/api/invoices` without a token successfully produces:

{"status_code":401,"error":"Unauthorized","description":"Unauthorized"}

But using Postman to add the JWT as `Token` to the header produces this error:

![screen shot 2015-04-29 at 8 07 14 pm](https://cloud.githubusercontent.com/assets/8967467/7405712/6aa48c5c-eeab-11e4-866b-be34ee4affb1.png)

**Comment by Dania02525** [comment]
This must be a problem with the "includes," since it is the only thing Enumerated in the POST /api/invoices route.  I'll have a look at it this evening

**Comment by Dania02525** [comment]
Fixed the problem with the Enum/nil- when posting 'includes':[] was set up to be outside of 'data'.  You should now be able to post with the json given in the example.  Still need to fix tests to use JWT!
